server:
  port: 8080

spring:
  application:
    name: mini-project
  datasource:
    url: jdbc:postgresql://localhost:5432/demodb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
  mail:
    host: smtp.gmail.com
    port: 587
    username: errandoryan@gmail.com
    password: hnuznbzpxqionfdt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true